@startuml
title NixOS - Channel updates
header
https://github.com/drupol/nixos-processes
endheader

skinparam backgroundColor #d1ecf1

|#d1ecf1|Hydra|

start
  fork
    group Periodically
    if (Successful jobs found?) is (yes) then
      :Update channels>
    else (no)
    endif
    end group
  fork again
    group Periodically
    repeat
      |Hydra|
      :<&data-transfer-download> Pull changes from Github;
    repeat while (Change detected?) is (no) not (yes)
    end group

      if (Git branch) is (master) then
        fork
          #b5ffb5:<&task> New job **nixpkgs:trunk**;
          fork
            #lightblue:<&box> Build packages;
          fork again
           #orange:<&data-transfer-upload> Upload build artifacts;
          end fork
        fork again
         #b5ffb5:<&task> New job **nixos:trunk-combined**;
          fork
            #lightblue:<&box> Build packages;
            :<&layers> Build Nixos modules;
            :<&aperture> Run tests;
          fork again
            #orange:<&data-transfer-upload> Upload build artifacts;
          end fork
        fork again
          #b5ffb5:<&task> New job **nixos:unstable-small**;
          fork
            #lightskyblue:<&box> Build packages;
            :<&layers> Build Nixos modules;
            :<&aperture> Run tests;

          fork again
            #orange:<&data-transfer-upload> Upload build artifacts;
          end fork
        end merge
      endif

      if (Git branch) is (staging) then
        fork
          #b5ffb5:<&task> New job **nixos:staging-small**;
          fork
            #lightskyblue:<&box> Build packages;
            :<&layers> Build Nixos modules;
            :<&aperture> Run tests;

          fork again
           #orange:<&data-transfer-upload> Upload build artifacts;
          end fork
        end merge
      endif

      if (Git branch) is (staging-next) then
        fork
          #b5ffb5:<&task> New job **nixpkgs:staging-next**;
          fork
            #lightblue:<&box> Build packages;
          fork again
           #orange:<&data-transfer-upload> Upload build artifacts;
          end fork
        fork again
          #b5ffb5:<&task> New job **nixos:staging-next-small**;
          fork
            #lightskyblue:<&box> Build packages;
          fork again
           #orange:<&data-transfer-upload> Upload build artifacts;
          end fork
        end merge
      endif

      if (Git branch) is (release-22.05) then
        fork
          #b5ffb5:<&task> New job **nixos:release-22.05**;
          fork
            #lightblue:<&box> Build packages;
            :<&layers> Build Nixos modules;
            :<&aperture> Run tests;
          fork again
           #orange:<&data-transfer-upload> Upload build artifacts;
          end fork
        fork again
          #b5ffb5:<&task> New job **nixos:release-22.05-small**;
          fork
            #lightskyblue:<&box> Build packages;
            :<&layers> Build Nixos modules;
            :<&aperture> Run tests;
          fork again
           #orange:<&data-transfer-upload> Upload build artifacts;
          end fork
        fork again
          #b5ffb5:<&task> New job **nixos:release-22.05-aarch64**;
          fork
            #lightblue:<&box> Build packages;
            :<&layers> Build Nixos modules;
            :<&aperture> Run tests;
          fork again
           #orange:<&data-transfer-upload> Upload build artifacts;
          end fork
        fork again
          #b5ffb5:<&task> New job **nixos:release-22.05-darwin**;
          fork
            #lightblue:<&box> Build packages;
            :<&layers> Build Nixos modules;
            :<&aperture> Run tests;
          fork again
           #orange:<&data-transfer-upload> Upload build artifacts;
          end fork
        end merge
      endif

  end merge

end

legend
|= |= Type |
| <#lightblue> <&box> | Normal package set |
| <#lightskyblue> <&box> | Limited package set |
| <#orange> <&data-transfer-upload> | Upload build artifacts to cache.nixos.org |
| <#b5ffb5> <&task> | Hydra jobset name |
endlegend

@enduml
