@startmindmap
title NixOS - Hydra branches and jobsets
header
https://github.com/drupol/nixos-processes
endheader

<style>
mindmapDiagram {
  :depth(0) {
    BackGroundColor d1ecf1
  }
  :depth(1) {
    BackGroundColor 4078c0
  }
  :depth(2) {
    BackGroundColor b5ffb5
  }
}
</style>

* <&droplet>Hydra
** <&fork>master
*** <&task> nixpkgs:trunk
**** <&box> Packages
*** <&task> nixos:trunk-combined
**** <&box> Packages
**** <&layers> NixOS modules
**** <&aperture> NixOS tests
*** <&task> nixos:unstable-small
**** <&box> Limited packages set
**** <&layers> NixOS modules
**** <&aperture> NixOS tests
** <&fork>staging
*** <&task> nixos:staging-small
**** <&box> Packages
**** <&layers> NixOS modules
**** <&aperture> NixOS tests
** <&fork>staging-next
*** <&task> nixpkgs:staging-next
**** <&box> Limited packages set
*** <&task> nixos:staging-next-small
**** <&box> Limited packages set
**** <&layers> NixOS modules
**** <&aperture> NixOS tests
** <&fork>release-22.05
*** <&task> nixos:release-22.05
**** <&box> Packages
**** <&layers> NixOS modules
**** <&aperture> NixOS tests
*** <&task> nixos:release-22.05-small
**** <&box> Limited packages set
**** <&layers> NixOS modules
**** <&aperture> NixOS tests
*** <&task> nixos:release-22.05-aarch64
**** <&box> Packages
**** <&layers> NixOS modules
**** <&aperture> NixOS tests
*** <&task> nixos:release-22.05-darwin
**** <&cog> x86_64-darwin
**** <&cog> aarch64-darwin

legend
|= |= Type |
| <#4078c0> <&fork> | Git branch |
| <#b5ffb5> <&task> | Hydra jobset |
endlegend

@endmindmap
