@startmindmap
title NixOS - Hydra branches and jobsets

<style>
mindmapDiagram {
  :depth(0) {
    BackGroundColor d1ecf1
  }
  :depth(1) {
    BackGroundColor 4078c0
  }
}
</style>

* <&droplet>Hydra
** <&fork>master
*** <&task> nixpkgs:trunk
**** <&box> Packages
*** <&task> nixos:trunk-combined
**** <&box> Packages
**** <&layers> Nixos modules
**** <&aperture> Tests
*** <&task> nixos:unstable-small
**** <&box> Limited packages set
**** <&layers> Nixos modules
**** <&aperture> Tests
** <&fork>staging
*** <&task> nixpkgs:staging-small
** <&fork>staging-next
*** <&task> nixpkgs:staging-next
** <&fork>release-22.05
*** <&task> nixos:release-22.05
**** <&box> Packages
**** <&layers> Nixos modules
**** <&aperture> Tests
*** <&task> nixos:release-22.05-small
**** <&box> Limited packages set
**** <&layers> Nixos modules
**** <&aperture> Tests
*** <&task> nixos:release-22.05-aarch64
*** <&task> nixos:release-22.05-darwin
**** <&cog> x86_64-darwin
**** <&cog> aarch64-darwin
@endmindmap
