@startuml Nixos - Life of a pull request
header
https://github.com/drupol/nixos-processes
endheader
!pragma useVerticalIf on

title NixOS - Life of a pull request

|#d1ecf1|Hydra|
|#4078c0|Github|
|#grey|Maintainer|
|#white|Contributor|

|Contributor|
start
  #238636:<&plus> Submit new PR against master branch;

  |Github|
  :<&bell> CI: Request review from code owners;

  |Contributor|
  repeat
    repeat
      label Here
      backward :<&fork> Update commit(s)>
      |Github|
      fork
      :CI: Editorconfig checks>
      fork again
      :CI: Basic release checks>
      fork again
      :CI: Manual (doc) tests>
      fork again
      if (PR against branch **nixos-***?) is (yes) then
        :CI: Display warning;
      else (no)
      endif
      fork again
      :CI: Webhook to ofBorg;
      end merge
      |Contributor|
    repeat while (Build is green?) is (<color:#f85149>no) not (<color:#238636>yes)

    repeat
    :<&clock> Wait for approvals;
    backward :<&chat> Post message on Matrix or Discourse>
    repeat while (Waiting too long?) is (yes) not (no)
    |Maintainer|
    :<&pencil> Make review>
    |Contributor|
    backward :<&fork> Update commit(s)>
  repeat while (Changes requested?) is (yes) not (no)
  |Maintainer|
  if (PR) is (is invalid) then
    #f85149:<&ban> Close PR>
    stop
  else (is valid)
  endif
  #238636:<&check> Approve PR;

  |Maintainer|
  #8957e5:<&fork> Merge PR;

  fork
  |Github|
  if (PR has backport labels?) is (yes) then
    :<&plus> CI: Create backport PR>
  else (no)
  endif
  fork again
  |Maintainer|
  :<&heart> Thanks the contributor;
  end fork

  |Hydra|
  :<&bolt> Start new build job;
  :<&task> Build specific jobset>
  if (Evaluation is green?) is (no) then

  stop
  else (yes)
  endif

  :<&cog> Trigger procedure to update channel and git branch>
end
@enduml
