@startuml Nixos - Life of a pull request
skinparam defaultTextAlignment center
skinparam swimlaneWidth same
skinparam linetype polyline
skinparam linetype ortho

title NixOS - Life of a pull request

|#4078c0|Github|
|#white|Contributor|
|#grey|Maintainer|
|#d1ecf1|Hydra|

|Contributor|
start
  :Submit a PR against master branch;

  repeat
    repeat
      backward :Add commit(s);
      |Github|
      :Trigger CI>
      |Contributor|
    repeat while (Build is green?) is (no) not (yes)
    :Wait for approvals;
    |Maintainer|
    :Make review>
  |Contributor|
  backward :Add commit(s);
  repeat while (Changes requested?) is (yes) not (no)
  |Maintainer|
  :Approve PR;

  |Maintainer|
  :Merge PR to master branch;

  |Hydra|
  :Start to build new job nixpkgs/trunk/unstable;
  :Build derivations;

  if (Evaluation is green?) is (no) then
  stop
  endif

  :Upload build artifacts to cache server;
  :Merge master branch in nixpkgs-unstable branch;
end
@enduml
